name: 'go-user-api'

services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - '${DATABASE_PORT}:5432'
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d ${POSTGRES_DB:-$DATABASE_NAME} -U ${POSTGRES_USER:-$DATABASE_USER}']
      interval: 5s
      timeout: 2s
      retries: 15
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: